import type { LegacyRelationMapping } from './legacy-migration.types';

const map = (
  sourceTable: string,
  domain: LegacyRelationMapping['domain'],
  targetTables: readonly string[],
  requiredColumns: readonly string[],
  options: Partial<
    Omit<LegacyRelationMapping, 'sourceTable' | 'domain' | 'targetTables' | 'requiredColumns'>
  > = {},
): LegacyRelationMapping => ({
  sourceTable,
  domain,
  targetTables,
  requiredColumns,
  disposition: 'map',
  rationaleCode: 'DIRECT_SUPPORTED_MAPPING',
  ...options,
});

/**
 * Authoritative Step 00 relation disposition. Unknown source columns are a
 * blocking drift condition; optional columns are the two configured-schema
 * variants inspected during the audit.
 */
export const LEGACY_RELATION_MAPPINGS: readonly LegacyRelationMapping[] = [
  map('users', 'identity', ['users'], ['id', 'email', 'password_hash', 'created_at'], {
    optionalColumns: [
      'full_name',
      'date_of_birth',
      'onboard_step',
      'needs_tutorial',
      'theme',
      'desired_language',
      'role',
      'status',
      'deactivated_at',
      'full_name_search',
      'email_verified_at',
      'email_verification_token',
      'email_verification_sent_at',
    ],
    ownerColumn: 'id',
  }),
  map(
    'user_passkeys',
    'identity',
    ['passkeys'],
    [
      'id',
      'user_id',
      'credential_id',
      'public_key_pem',
      'sign_count',
      'label',
      'created_at',
      'last_used',
    ],
    { ownerColumn: 'user_id' },
  ),
  map(
    'user_login_activity',
    'identity',
    ['login_audit_events'],
    ['id', 'user_id', 'email', 'success', 'method', 'ip_address', 'user_agent', 'created_at'],
    { ownerColumn: 'user_id' },
  ),
  map(
    'user_remember_tokens',
    'identity',
    [],
    ['id', 'user_id', 'selector', 'token_hash', 'expires_at', 'created_at'],
    {
      disposition: 'discard_security_secret',
      rationaleCode: 'REMEMBER_TOKENS_INVALIDATED',
      ownerColumn: 'user_id',
    },
  ),
  map('currencies', 'currency', ['currencies'], ['code', 'name']),
  map('user_currencies', 'currency', ['user_currencies'], ['user_id', 'code', 'is_main'], {
    ownerColumn: 'user_id',
    currencyColumn: 'code',
  }),
  map('fx_rates', 'currency', ['fx_quotes'], ['rate_date', 'base_code', 'code', 'rate'], {
    currencyColumn: 'code',
  }),
  map(
    'cashflow_rules',
    'budgeting',
    ['budget_rules'],
    ['id', 'user_id', 'label', 'percent', 'target_hint'],
    {
      ownerColumn: 'user_id',
      amountColumn: 'percent',
    },
  ),
  map('categories', 'budgeting', ['categories'], ['id', 'user_id', 'label', 'kind'], {
    optionalColumns: ['color', 'cashflow_rule_id', 'system_key', 'protected'],
    ownerColumn: 'user_id',
  }),
  map(
    'basic_incomes',
    'budgeting',
    ['basic_incomes'],
    ['id', 'user_id', 'label', 'amount', 'currency', 'valid_from', 'valid_to'],
    {
      optionalColumns: ['category_id'],
      ownerColumn: 'user_id',
      amountColumn: 'amount',
      currencyColumn: 'currency',
    },
  ),
  map(
    'transactions',
    'ledger',
    ['journal_entries', 'journal_legs', 'fx_conversion_snapshots'],
    [
      'id',
      'user_id',
      'kind',
      'category_id',
      'amount',
      'currency',
      'occurred_on',
      'note',
      'created_at',
      'updated_at',
    ],
    {
      optionalColumns: [
        'main_currency',
        'fx_rate_to_main',
        'amount_main',
        'source',
        'source_ref_id',
        'locked',
        'ef_tx_id',
      ],
      ownerColumn: 'user_id',
      amountColumn: 'amount',
      currencyColumn: 'currency',
      rationaleCode: 'CORRECTED_LEDGER_MAPPING',
    },
  ),
  map(
    'scheduled_payments',
    'recurrence',
    ['recurring_rules'],
    ['id', 'user_id', 'title', 'amount', 'currency', 'rrule', 'next_due'],
    {
      optionalColumns: ['category_id', 'loan_id', 'goal_id', 'investment_id', 'archived_at'],
      ownerColumn: 'user_id',
      amountColumn: 'amount',
      currencyColumn: 'currency',
    },
  ),
  map(
    'goals',
    'goals',
    ['goals', 'ledger_accounts'],
    [
      'id',
      'user_id',
      'title',
      'target_amount',
      'current_amount',
      'currency',
      'deadline',
      'priority',
      'status',
    ],
    {
      optionalColumns: ['archived_at', 'category_id'],
      ownerColumn: 'user_id',
      amountColumn: 'target_amount',
      currencyColumn: 'currency',
    },
  ),
  map(
    'goal_contributions',
    'goals',
    ['goal_contributions', 'journal_entries', 'journal_legs'],
    ['id', 'user_id', 'goal_id', 'amount', 'currency', 'occurred_on', 'note', 'created_at'],
    {
      ownerColumn: 'user_id',
      amountColumn: 'amount',
      currencyColumn: 'currency',
      rationaleCode: 'RECLASSIFIED_INTERNAL_TRANSFER',
    },
  ),
  map(
    'goal_transactions',
    'goals',
    ['goal_contributions', 'journal_entries', 'journal_legs'],
    ['id', 'user_id', 'goal_id', 'occurred_on', 'amount', 'currency', 'note'],
    {
      disposition: 'deduplicate',
      ownerColumn: 'user_id',
      amountColumn: 'amount',
      currencyColumn: 'currency',
      rationaleCode: 'LEGACY_DUPLICATE_MOVEMENT',
    },
  ),
  map(
    'emergency_fund',
    'emergency_reserve',
    ['emergency_reserves', 'ledger_accounts'],
    ['user_id', 'target_amount', 'currency', 'total'],
    {
      optionalColumns: ['investment_id'],
      ownerColumn: 'user_id',
      amountColumn: 'target_amount',
      currencyColumn: 'currency',
      rationaleCode: 'DERIVE_BALANCE_FROM_MOVEMENTS',
    },
  ),
  map(
    'emergency_fund_tx',
    'emergency_reserve',
    ['emergency_reserve_movements', 'journal_entries', 'journal_legs'],
    [
      'id',
      'user_id',
      'occurred_on',
      'kind',
      'amount_native',
      'currency_native',
      'amount_main',
      'main_currency',
      'rate_used',
      'note',
    ],
    {
      optionalColumns: ['investment_tx_id'],
      ownerColumn: 'user_id',
      amountColumn: 'amount_native',
      currencyColumn: 'currency_native',
      rationaleCode: 'RECLASSIFIED_INTERNAL_TRANSFER',
    },
  ),
  map(
    'emergency_transactions',
    'emergency_reserve',
    ['emergency_reserve_movements', 'journal_entries', 'journal_legs'],
    ['id', 'user_id', 'occurred_on', 'amount', 'kind', 'note'],
    {
      disposition: 'deduplicate',
      ownerColumn: 'user_id',
      amountColumn: 'amount',
      rationaleCode: 'LEGACY_DUPLICATE_MOVEMENT',
    },
  ),
  map(
    'loans',
    'loans',
    ['loans', 'ledger_accounts'],
    [
      'id',
      'user_id',
      'name',
      'principal',
      'interest_rate',
      'start_date',
      'end_date',
      'payment_day',
      'extra_payment',
      'balance',
    ],
    {
      optionalColumns: [
        'currency',
        'scheduled_payment_id',
        'insurance_monthly',
        'history_confirmed',
        'finished_at',
        'archived_at',
      ],
      ownerColumn: 'user_id',
      amountColumn: 'principal',
      currencyColumn: 'currency',
    },
  ),
  map(
    'loan_payments',
    'loans',
    ['loan_payments', 'journal_entries', 'journal_legs'],
    ['id', 'loan_id', 'paid_on', 'amount', 'principal_component', 'interest_component', 'currency'],
    {
      optionalColumns: ['transaction_id'],
      amountColumn: 'amount',
      currencyColumn: 'currency',
    },
  ),
  map(
    'investments',
    'investments',
    ['investments', 'ledger_accounts'],
    [
      'id',
      'user_id',
      'type',
      'name',
      'provider',
      'identifier',
      'interest_rate',
      'notes',
      'created_at',
      'updated_at',
      'balance',
      'currency',
      'interest_frequency',
    ],
    {
      optionalColumns: ['stock_id', 'units'],
      ownerColumn: 'user_id',
      currencyColumn: 'currency',
      rationaleCode: 'SCENARIO_AND_DERIVED_BALANCE_MAPPING',
    },
  ),
  map(
    'investment_transactions',
    'investments',
    ['investment_movements', 'journal_entries', 'journal_legs'],
    ['id', 'investment_id', 'user_id', 'amount', 'note', 'created_at'],
    {
      ownerColumn: 'user_id',
      amountColumn: 'amount',
      rationaleCode: 'SIGNED_AMOUNT_TO_DIRECTION',
    },
  ),
  map(
    'stocks',
    'securities',
    ['securities_instruments'],
    [
      'id',
      'symbol',
      'exchange',
      'market',
      'name',
      'currency',
      'sector',
      'industry',
      'beta',
      'created_at',
      'updated_at',
    ],
  ),
  map(
    'stock_trades',
    'securities',
    [
      'securities_trades',
      'securities_lots',
      'securities_positions',
      'journal_entries',
      'journal_legs',
    ],
    ['id', 'user_id', 'symbol', 'trade_on', 'side', 'quantity', 'price', 'currency'],
    {
      optionalColumns: [
        'stock_id',
        'executed_at',
        'fee',
        'note',
        'market',
        'created_at',
        'updated_at',
      ],
      ownerColumn: 'user_id',
      currencyColumn: 'currency',
    },
  ),
  map(
    'stock_cash_movements',
    'securities',
    ['securities_cash_movements', 'journal_entries', 'journal_legs'],
    ['id', 'user_id', 'amount', 'currency', 'executed_at', 'note', 'created_at'],
    {
      ownerColumn: 'user_id',
      amountColumn: 'amount',
      currencyColumn: 'currency',
    },
  ),
  map(
    'stock_positions',
    'securities',
    [],
    [
      'id',
      'user_id',
      'stock_id',
      'qty',
      'avg_cost_ccy',
      'avg_cost_currency',
      'cash_impact_ccy',
      'created_at',
      'updated_at',
    ],
    {
      disposition: 'discard_derived',
      ownerColumn: 'user_id',
      rationaleCode: 'REBUILD_SECURITIES_DERIVED_STATE',
    },
  ),
  map(
    'stock_lots',
    'securities',
    [],
    [
      'id',
      'position_id',
      'qty_open',
      'qty_closed',
      'open_price',
      'fee',
      'opened_at',
      'closed_at',
      'created_at',
      'updated_at',
    ],
    {
      disposition: 'discard_derived',
      rationaleCode: 'REBUILD_FIFO_FROM_TRADES',
    },
  ),
  map(
    'stock_realized_pl',
    'securities',
    [],
    [
      'id',
      'user_id',
      'stock_id',
      'sell_trade_id',
      'realized_pl_base',
      'realized_pl_ccy',
      'currency',
      'method',
      'qty_closed',
      'closed_at',
      'created_at',
    ],
    {
      disposition: 'discard_derived',
      ownerColumn: 'user_id',
      rationaleCode: 'REBUILD_FIFO_FROM_TRADES',
    },
  ),
  map(
    'stock_prices_last',
    'securities',
    [],
    [
      'stock_id',
      'last',
      'prev_close',
      'day_high',
      'day_low',
      'volume',
      'provider_ts',
      'stale',
      'updated_at',
    ],
    {
      disposition: 'discard_derived',
      rationaleCode: 'REIMPORT_MARKET_DATA_WITH_PROVENANCE',
    },
  ),
  map(
    'price_daily',
    'securities',
    ['securities_daily_prices'],
    ['id', 'stock_id', 'date', 'open', 'high', 'low', 'close', 'volume', 'provider', 'created_at'],
  ),
  map(
    'watchlist',
    'securities',
    ['securities_watchlist'],
    ['id', 'user_id', 'stock_id', 'created_at'],
    { ownerColumn: 'user_id' },
  ),
  map(
    'user_settings_stocks',
    'securities',
    [],
    ['user_id', 'unrealized_method', 'realized_method', 'target_allocations', 'refresh_seconds'],
    {
      disposition: 'quarantine',
      ownerColumn: 'user_id',
      rationaleCode: 'NO_APPROVED_TARGET_SETTINGS_MODEL',
    },
  ),
  map(
    'stock_portfolio_snapshots',
    'securities',
    [],
    ['id', 'user_id', 'snapshot_on', 'total_value_base', 'created_at'],
    {
      disposition: 'discard_derived',
      ownerColumn: 'user_id',
      rationaleCode: 'UNPROVEN_VALUATION_PROVENANCE',
    },
  ),
  map(
    'feedback',
    'feedback',
    ['feedback'],
    ['id', 'user_id', 'kind', 'title', 'message', 'severity', 'status', 'created_at', 'updated_at'],
    { ownerColumn: 'user_id' },
  ),
  map(
    'feedback_responses',
    'feedback',
    ['feedback_responses'],
    ['id', 'feedback_id', 'admin_id', 'message', 'created_at', 'updated_at'],
  ),
  map(
    'roles',
    'administration',
    [],
    ['id', 'slug', 'name', 'description', 'is_system', 'capabilities', 'created_at', 'updated_at'],
    {
      disposition: 'discard_unsupported',
      rationaleCode: 'FIXED_ROLES_ONLY',
    },
  ),
  map(
    'system_settings',
    'administration',
    ['system_settings'],
    [
      'id',
      'site_name',
      'primary_url',
      'support_email',
      'contact_email',
      'logo_url',
      'favicon_url',
      'maintenance_mode',
      'maintenance_message',
      'created_at',
      'updated_at',
    ],
  ),
  map(
    'api_integrations',
    'administration',
    [],
    [
      'id',
      'name',
      'service',
      'api_key_encrypted',
      'status',
      'metadata',
      'last_used_at',
      'created_at',
      'updated_at',
    ],
    {
      disposition: 'discard_security_secret',
      rationaleCode: 'PROVIDER_CREDENTIALS_MUST_BE_REENTERED',
    },
  ),
  map(
    'billing_settings',
    'billing',
    [],
    [
      'id',
      'stripe_secret_key',
      'stripe_publishable_key',
      'stripe_webhook_secret',
      'default_currency',
      'created_at',
      'updated_at',
    ],
    {
      disposition: 'discard_security_secret',
      rationaleCode: 'BILLING_SECRETS_NOT_MIGRATED',
    },
  ),
  map(
    'billing_plans',
    'billing',
    ['billing_plans'],
    [
      'id',
      'code',
      'name',
      'description',
      'price',
      'currency',
      'billing_interval',
      'interval_count',
      'role_slug',
      'trial_days',
      'is_active',
      'stripe_product_id',
      'stripe_price_id',
      'metadata',
      'created_at',
      'updated_at',
    ],
    {
      amountColumn: 'price',
      currencyColumn: 'currency',
    },
  ),
  map(
    'billing_promotions',
    'billing',
    ['billing_promotions'],
    [
      'id',
      'code',
      'name',
      'description',
      'discount_percent',
      'discount_amount',
      'currency',
      'max_redemptions',
      'redeem_by',
      'trial_days',
      'plan_code',
      'stripe_coupon_id',
      'stripe_promo_code_id',
      'metadata',
      'created_at',
      'updated_at',
    ],
    {
      amountColumn: 'discount_amount',
      currencyColumn: 'currency',
    },
  ),
  map(
    'user_subscriptions',
    'billing',
    ['user_subscriptions'],
    [
      'id',
      'user_id',
      'plan_code',
      'plan_name',
      'status',
      'billing_interval',
      'interval_count',
      'amount',
      'currency',
      'started_at',
      'current_period_start',
      'current_period_end',
      'cancel_at',
      'canceled_at',
      'trial_ends_at',
      'notes',
      'created_at',
      'updated_at',
    ],
    {
      ownerColumn: 'user_id',
      amountColumn: 'amount',
      currencyColumn: 'currency',
    },
  ),
  map(
    'user_invoices',
    'billing',
    ['user_invoices'],
    [
      'id',
      'user_id',
      'subscription_id',
      'invoice_number',
      'status',
      'total_amount',
      'currency',
      'issued_at',
      'due_at',
      'paid_at',
      'failure_reason',
      'refund_reason',
      'notes',
      'created_at',
      'updated_at',
    ],
    {
      ownerColumn: 'user_id',
      amountColumn: 'total_amount',
      currencyColumn: 'currency',
    },
  ),
  map(
    'user_payments',
    'billing',
    ['user_payments'],
    [
      'id',
      'user_id',
      'invoice_id',
      'type',
      'status',
      'amount',
      'currency',
      'gateway',
      'transaction_reference',
      'failure_reason',
      'notes',
      'processed_at',
      'created_at',
      'updated_at',
    ],
    {
      ownerColumn: 'user_id',
      amountColumn: 'amount',
      currencyColumn: 'currency',
    },
  ),
  map(
    'email_templates',
    'notifications',
    ['email_templates'],
    [
      'id',
      'code',
      'name',
      'subject',
      'body',
      'locale',
      'last_tested_at',
      'created_at',
      'updated_at',
    ],
  ),
  map(
    'notification_channels',
    'notifications',
    ['email_channel_settings'],
    ['id', 'channel', 'name', 'is_enabled', 'config', 'created_at', 'updated_at'],
    {
      rationaleCode: 'EMAIL_ONLY_PROVIDER_REVIEW',
    },
  ),
  map('baby_steps', 'removed', [], ['user_id', 'step', 'status', 'note'], {
    disposition: 'quarantine',
    ownerColumn: 'user_id',
    rationaleCode: 'UNSUPPORTED_BABY_STEPS',
  }),
  map('schema_migrations', 'removed', [], ['filename', 'run_at'], {
    disposition: 'discard_derived',
    rationaleCode: 'SOURCE_VERSION_EVIDENCE_ONLY',
  }),
] as const;

export const LEGACY_MAPPING_BY_TABLE = new Map(
  LEGACY_RELATION_MAPPINGS.map((mapping) => [mapping.sourceTable, mapping]),
);
