name: Deploy to Nethely (production)

on:
    push:
        branches: ['production']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Write SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.NETHELY_SSH_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

            - name: Trust Nethely host key
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -p "${{ secrets.NETHELY_SSH_PORT }}" "${{ secrets.NETHELY_SSH_HOST }}" >> ~/.ssh/known_hosts
                  chmod 600 ~/.ssh/known_hosts

            - name: Deploy via rsync
              run: |
                  rsync -az --delete \
                    --exclude='.git/' \
                    --exclude='.github/' \
                    --exclude='.env' \
                    --exclude='.env.*' \
                    -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.NETHELY_SSH_PORT }}" \
                    ./ "${{ secrets.NETHELY_SSH_USER }}@${{ secrets.NETHELY_SSH_HOST }}:${{ secrets.NETHELY_DEPLOY_PATH }}"
